CREATE SCHEMA IF NOT EXISTS rp;

DROP TABLE IF EXISTS rp.newsfeed CASCADE;
CREATE TABLE rp.newsfeed (
  id SERIAL PRIMARY KEY,
  title TEXT,
  artist TEXT,
  inst TEXT
);

DROP TABLE IF EXISTS rp.user CASCADE;
CREATE TABLE rp.user (
  id SERIAL PRIMARY KEY,
  uid TEXT,
  pw TEXT
);
