language: node_js
node_js:
  - "6"
after_script:
- npm uninstall babel && npm i babel-cli && ./node_modules/.bin/babel-node ./node_modules/istanbul/lib/cli.js cover ./node_modules/.bin/_mocha -- -R spec src/test/**/* && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js