[package]
name = "server"
version = "0.1.0"
authors = ["Kevin Han <dltmd6262@kaist.ac.kr>"]

[dependencies]
iron = "*"
router = "*"
bodyparser = "*"
time = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
postgres = "*"

[dev-dependencies]
stainless = "*"
